### PR TITLE
Deprecate Gen-taking forAllNoShrink

### PR DESCRIPTION
**Pull request by dwijnand**
Swap the impls, so the deprecated API calls the not deprecated API.

### CODE REVIEW

**Comment by charleso** [comment]
I think I'd worry about the impact of this change a little more. Not because it's not a good thing to do (it is), but because if someone has deprecated warnings as errors turned on (like we do for our projects), this is going to require lots of refactoring.

Thoughts?

**Comment by dwijnand** [comment]
> Thoughts?

My thoughts are that `-Xfatal-warnings` is a very blunt tool, which always has that effect.  It's a sad state of affairs, and one we should fix, but I don't think it should halt changes like this, at least not always.

**Comment by dwijnand** [comment]
Oh!  Reading https://github.com/scala/bug/issues/8410 it looks like you can disable deprecation warnings with `-deprecation:false`?  TIL.  So that's the stopgap you can use while transitioning.  It's still a little blunt (being all deprecation warnings), but it's something.

**Comment by charleso** [comment]
> but I don't think it should halt changes like this, at least not always.

Fair enough. I love `-Xfatal-warnings` for the most part, but the lack of finer controls for ignoring deprecation warnings is sorely missing.

**Comment by dwijnand** [comment]
It might finally be coming: https://github.com/scala/scala-dev/issues/333

**Comment by charleso** [comment]
> It might finally be coming: scala/scala-dev#333

Awesome! Thanks for the link, that's good to know.

**Pull request merged**
